apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiS2lyaWxsLVk4OCIsInBhc3N3b3JkIjoiZ2hwX2VadXdHem1USnR3d1l6MHplcnFKY0hVaU1oMzBoeTQ2VVFFNyIsImF1dGgiOiJTMmx5YVd4c0xWazRPRHBuYUhCZlpWcDFkMGQ2YlZSS2RIZDNXWG93ZW1WeWNVcGpTRlZwVFdnek1HaDVORFpWVVVVMyJ9fX0=
type: kubernetes.io/dockerconfigjson
